# Generated by Django 3.2.7 on 2021-10-08 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyRates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RUB', models.FloatField(null=True)),
                ('EUR', models.FloatField(null=True)),
                ('USD', models.FloatField(null=True)),
            ],
        ),
    ]
