# Generated by Django 3.2.7 on 2021-10-08 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0002_currencyrates'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencyrates',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
