# Generated by Django 3.2.7 on 2021-12-09 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0004_accounthistory_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounthistory',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
