# Generated by Django 3.2.7 on 2021-12-18 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0006_alter_accounthistory_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounthistory',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='apiapp.account'),
            preserve_default=False,
        ),
    ]
