# Generated by Django 3.2.7 on 2021-12-28 13:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0007_accounthistory_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounthistory',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='apiapp.account'),
        ),
        migrations.AlterField(
            model_name='accounthistory',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history', to='apiapp.category'),
        ),
        migrations.AlterField(
            model_name='accounthistory',
            name='date',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
    ]
